### ISSUE TITLE
Переименовать проэкт

### ISSUE THREAD

**Issue by razzeeyy** [severe-island/navee#1]
Нужно переименовать проект, т.к. префикс ng- социально занят за фреймворком Angular, а он довольно популярен и распространён, а следовательно и префикс. 

Предлагаемое название **VEE**: _Virtual Execution Environment_ или _Virtual Environment Enhanced_.

Что ещё необходимо сделать:
* Проверить предлагаемое название на коллизии.
* Удостовериться, что название не является зарегестрированным торговым знаком какой-либо компании.
* Возможно, что-то ещё, что я сейчас упускаю из вида.

Это поможет в дальнейшем снизить головную боль, особенно если случайно будет коллизия с торговым знаком или другим юридическим/общепризнанным понятием.

**Comment by easimonenko** [comment]
В словаре такого слова вроде нет, но вот коллизии:

- https://en.wikipedia.org/wiki/Draft:Virtual_Economy_Era
- https://en.wikipedia.org/wiki/VStar_Entertainment_Group

**Comment by easimonenko** [comment]
Как вот такое предложение: Next Age VEE (NAVEE)? Вероятно, что в английском так не говорят: next age.

**Comment by razzeeyy** [comment]
Забавно, мой изначально предложенный вариант как не странно давно успешно имеет коллизию.
http://www.wikicfp.com/cfp/program?id=2933&f=Virtual%20Execution%20Environments

NAVEE выглядит хорошо. И красиво созвучно с Na'Vi а это латинские слова Natus Vincere конкатеннированные.  
Next Age не говорят, насколько мне известно, а вот New Age довольно таки.  
__New Age Virtual Execution Enviroment__ -- звучит :)  

Голосую за переименовку в NAVEE.

**Comment by easimonenko** [comment]
Забавно, VEE это кажись конференция или исследования по виртуальным окружениям.

Да, мне тоже звучание нравится. И перевод: рождённый, чтобы победить. :)

Насчёт New Age знаю, тут другая ассоциация с одним американским движением. С другой стороны в переводе "новая эра" ничего особенного не подразумевает.

В общем, переименовываю в NAVEE.

**Comment by easimonenko** [comment]
Переименовал.
